language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
# command to run tests
script: nosetests
